### PR TITLE
Add CAE PR Creator Bot to allow list

### PR DESCRIPTION
**Pull request by jtracey93**
Add cae-pr-creator[bot] CAE (https:/aka.ms/caeinfra) team's bot to create PRs via GitHub App integration on our repos for automation tasks

### CODE REVIEW

**Comment by jtracey93** [comment]
@jeffwilcox @JohannesLampel @DragosDanielBoia could this be reviewed, approved and merged? As this app is now approved and installed on our required repos as per: https://github.com/microsoft/github-operations/issues/245

**Comment by jtracey93** [comment]
> @jeffwilcox Jeff Wilcox FTE @JohannesLampel Johannes Lampel FTE @DragosDanielBoia Dragos Boia FTE could this be reviewed, approved and merged? As this app is now approved and installed on our required repos as per: [microsoft/github-operations#245](https://github.com/microsoft/github-operations/issues/245)

Any updates here team?

**Review by jeffwilcox — APPROVED** [review]

**Comment by jeffwilcox** [comment]
I've approved this but don't have permission to merge this, so will need someone else to help.

**Review by JohannesLampel — APPROVED** [review]

**Comment by JohannesLampel** [comment]
Approved and merged, sorry for the delay.

**Pull request merged**
